build:snap:
  stage: build
  image: ubuntudesktop/gnome-3-28-1804
  script:
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - export SNAP_ARCH=amd64
    - export SNAPCRAFT_BUILD_INFO=1
    - apt-get update
    - apt-get install -y git
    - SNAPCRAFT_SETUP_CORE=1 snapcraft
    - |
       if [ "$CI_COMMIT_REF_NAME" = "master" ]; then
         echo "$LOGIN" | base64 --decode | snapcraft login --with -
         snapcraft push *.snap --release stable
         snapcraft logout
       fi
  allow_failure: false
  when: manual
  artifacts:
    paths: ['./*.snap']
    expire_in: 1 days
