name: gtk-theme-orchis
version: '2022-07-20'
summary: Orchis theme
description: |
  Snap of the Orchis theme

# We build against Ubuntu 22.04 packages, but use the "bare" base as
# we don't want to force installation of a large base snap.
build-base: core22
base: bare
grade: stable
confinement: strict

slots:
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Orchis
        - $SNAP/share/themes/Orchis-Light
        - $SNAP/share/themes/Orchis-Light-Compact
        - $SNAP/share/themes/Orchis-Dark
        - $SNAP/share/themes/Orchis-Dark-Compact
        - $SNAP/share/themes/Orchis-Compact

parts:
  theme:
    plugin: nil
    source: https://github.com/vinceliuice/Orchis-theme/archive/refs/tags/2022-07-20.tar.gz
    override-build: |
        snapcraftctl build
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/themes/
        $SNAPCRAFT_PART_SRC/install.sh -d $SNAPCRAFT_PART_INSTALL/share/themes/
